# Site settings
title: Not Mandatory
email: steve@notmandatory.org
gpg_fingerprint: E3DE 1EFC 18CC 0C9B 36E1  E146 4D70 01D3 C9BA D1F4
gpg_pubkey_file: /steve_notmandatory.gpg
description: > # this means to ignore newlines until "baseurl:"
  Steve Myers blog and current contact information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notmandatory.org" # the base hostname & protocol for your site
mastodon_username: notmandatory
mastodon_host: bitcoinhackers.org
twitter_username: notmandatory
bitbucket_username:  stevemyers

# Build settings
markdown: kramdown
