# The URL the site will be built for
base_url = "https://notmandatory.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_rss = true

title = "Not Mandatory"
description = "Steve Myers blog and current contact information."

taxonomies = [
       {name = "tags"},
       {name = "categories"},
     ]

[extra]
# Put all your custom variables here

title_image = "notmandatory.jpg"
github_username = "notmandatory"
twitter_username = "notmandatory"
mastodon_username = "notmandatory"
mastodon_host = "bitcoinhackers.org"
email = "steve@notmandatory.org"
gpg_fingerprint = "D9FF 9010 BE16 9B64 D3ED  CBF9 8105 A46B 22C2 D051"
gpg_pubkey_file = "/steve_notmandatory.gpg"